#!/bin/sh
# Build a fake Archivematica DIP that Binder's SWORD ingest
# (qtPackageExtractorMETSArchivematicaDIP) will process end-to-end without
# Archivematica.
#
# Creates:
#   uploads/sword-deposits/Demo_ingest-<AIPUUID>/
#     METS.<AIPUUID>.xml
#     objects/<FUUID1>-Demo_video.mov
#     objects/<FUUID2>-Demo_notes.txt
#
# uploads/ is part of the ..:/app bind mount, and the app container sets
# app_sword_deposit_dir to /app/uploads/sword-deposits (docker/app/entrypoint.sh),
# so the deposit's "Content-Location: file:///Demo_ingest-<AIPUUID>" resolves here.
#
# Fixed UUIDs keep the build idempotent. Note that Binder refuses to ingest the
# same AIP UUID twice ("There is already a AIP with the given UUID"), so a
# re-deposit needs the aip row deleted or a new UUID.
set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
DEPOSIT_ROOT="${SCRIPT_DIR}/../uploads/sword-deposits"

AIP_UUID="aaaaaaaa-bbbb-cccc-dddd-eeeeffff0001"
FUUID1="11111111-2222-3333-4444-555566660001"   # Demo_video.mov
FUUID2="11111111-2222-3333-4444-555566660002"   # Demo_notes.txt

DIP_NAME="Demo_ingest-${AIP_UUID}"
DIP_DIR="${DEPOSIT_ROOT}/${DIP_NAME}"

# Rebuild from scratch (idempotent)
rm -rf "${DIP_DIR}"
mkdir -p "${DIP_DIR}/objects"

# Access copies in the DIP: named <fileUUID>-<name>, because the extractor
# locates them with glob(objects/<fileUUID>*).
printf 'Fake video placeholder for Binder demo ingest (not a real QuickTime file).\n' \
  > "${DIP_DIR}/objects/${FUUID1}-Demo_video.mov"
printf 'Demo ingest notes.\nThis DIP was generated by docker/build-fake-dip.sh.\n' \
  > "${DIP_DIR}/objects/${FUUID2}-Demo_notes.txt"

SIZE1=$(wc -c < "${DIP_DIR}/objects/${FUUID1}-Demo_video.mov" | tr -d ' ')
SIZE2=$(wc -c < "${DIP_DIR}/objects/${FUUID2}-Demo_notes.txt" | tr -d ' ')

NOW=$(date -u '+%Y-%m-%dT%H:%M:%S')

# Minimal METS satisfying every XPath the extractor dereferences:
# - structMap TYPE="physical" (QubitMetsParser::getStructMap)
# - structMap div/div DMDID -> DC dmdSec with title (getMainDmdSec/processDmdSec)
# - fileSec fileGrp USE="original", file ID contains file UUID, ADMID -> amdSec
#   with PREMIS objectIdentifier UUID (getDipUploadMappings uuidMapping,
#   addMetsDataToInformationObject)
# - FLocat with xlink:href = relative path within AIP (title of the file IO)
# - metsHdr CREATEDATE (aip.createdAt), premis size (aip.sizeOnDisk)
# No dc:identifier in the main dmdSec: it would be treated as a TMS
# ComponentNumber (getAipRelatedComponentNumber). No PREMIS:AGENT sections:
# ingestion username lookup then returns null.
cat > "${DIP_DIR}/METS.${AIP_UUID}.xml" <<METS
<?xml version="1.0" encoding="UTF-8"?>
<mets:mets xmlns:mets="http://www.loc.gov/METS/"
           xmlns:premis="info:lc/xmlns/premis-v2"
           xmlns:dc="http://purl.org/dc/elements/1.1/"
           xmlns:dcterms="http://purl.org/dc/terms/"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:xlink="http://www.w3.org/1999/xlink">
  <mets:metsHdr CREATEDATE="${NOW}"/>
  <mets:dmdSec ID="dmdSec_1" CREATED="${NOW}">
    <mets:mdWrap MDTYPE="DC">
      <mets:xmlData>
        <dcterms:dublincore>
          <dc:title>Demo ingest DIP</dc:title>
          <dc:description>Fake Archivematica DIP built by docker/build-fake-dip.sh for the Binder spike.</dc:description>
        </dcterms:dublincore>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:amdSec ID="amdSec_1">
    <mets:techMD ID="techMD_1">
      <mets:mdWrap MDTYPE="PREMIS:OBJECT">
        <mets:xmlData>
          <premis:object xsi:type="premis:file">
            <premis:objectIdentifier>
              <premis:objectIdentifierType>UUID</premis:objectIdentifierType>
              <premis:objectIdentifierValue>${FUUID1}</premis:objectIdentifierValue>
            </premis:objectIdentifier>
            <premis:objectCharacteristics>
              <premis:size>${SIZE1}</premis:size>
              <premis:format>
                <premis:formatDesignation>
                  <premis:formatName>QuickTime</premis:formatName>
                </premis:formatDesignation>
              </premis:format>
            </premis:objectCharacteristics>
            <premis:originalName>%transferDirectory%objects/Demo_video.mov</premis:originalName>
          </premis:object>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:techMD>
  </mets:amdSec>
  <mets:amdSec ID="amdSec_2">
    <mets:techMD ID="techMD_2">
      <mets:mdWrap MDTYPE="PREMIS:OBJECT">
        <mets:xmlData>
          <premis:object xsi:type="premis:file">
            <premis:objectIdentifier>
              <premis:objectIdentifierType>UUID</premis:objectIdentifierType>
              <premis:objectIdentifierValue>${FUUID2}</premis:objectIdentifierValue>
            </premis:objectIdentifier>
            <premis:objectCharacteristics>
              <premis:size>${SIZE2}</premis:size>
              <premis:format>
                <premis:formatDesignation>
                  <premis:formatName>Plain Text File</premis:formatName>
                </premis:formatDesignation>
              </premis:format>
            </premis:objectCharacteristics>
            <premis:originalName>%transferDirectory%objects/Demo_notes.txt</premis:originalName>
          </premis:object>
        </mets:xmlData>
      </mets:mdWrap>
    </mets:techMD>
  </mets:amdSec>
  <mets:fileSec>
    <mets:fileGrp USE="original">
      <mets:file ID="file-${FUUID1}" GROUPID="Group-${FUUID1}" ADMID="amdSec_1">
        <mets:FLocat xlink:href="objects/Demo_video.mov" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
      <mets:file ID="file-${FUUID2}" GROUPID="Group-${FUUID2}" ADMID="amdSec_2">
        <mets:FLocat xlink:href="objects/Demo_notes.txt" LOCTYPE="OTHER" OTHERLOCTYPE="SYSTEM"/>
      </mets:file>
    </mets:fileGrp>
  </mets:fileSec>
  <mets:structMap TYPE="physical" ID="structMap_1" LABEL="Archivematica default">
    <mets:div TYPE="Directory" LABEL="${DIP_NAME}">
      <mets:div TYPE="Directory" LABEL="objects" DMDID="dmdSec_1">
        <mets:div TYPE="Item" LABEL="Demo_video.mov">
          <mets:fptr FILEID="file-${FUUID1}"/>
        </mets:div>
        <mets:div TYPE="Item" LABEL="Demo_notes.txt">
          <mets:fptr FILEID="file-${FUUID2}"/>
        </mets:div>
      </mets:div>
    </mets:div>
  </mets:structMap>
</mets:mets>
METS

# Must be readable by the app/worker containers (grab() checks is_readable)
chmod -R a+rX "${DEPOSIT_ROOT}"

echo "Fake DIP built at: ${DIP_DIR}"
echo "  METS.${AIP_UUID}.xml"
echo "  objects/${FUUID1}-Demo_video.mov (${SIZE1} bytes)"
echo "  objects/${FUUID2}-Demo_notes.txt (${SIZE2} bytes)"
echo "Inside the containers this is /app/uploads/sword-deposits/${DIP_NAME}"
echo "Next: docker/deposit-fake-dip.sh"
