<?php

/*
 * This file is part of the Access to Memory (AtoM) software.
 *
 * Access to Memory (AtoM) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Access to Memory (AtoM) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Access to Memory (AtoM).  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Attach real artwork images (private demo assets) to seeded DRMC file IOs
 * as image digital objects, so the context browser sidebar file gallery
 * (thumbnails mode) can render real previews.
 *
 * Asset layout: uploads/r/drmc-assets/{identifier}/*.jpg|jpeg|png
 * where {identifier} is the artwork identifier (e.g. 81362 = Lovers).
 *
 * For each asset image found:
 *  - skipped if a digital object with the same (sanitized) filename already
 *    exists anywhere under the artwork (idempotent, safe to re-run)
 *  - otherwise attached to the first descendant file IO (digital object LOD)
 *    with an image-extension title and no digital object yet — image DOs are
 *    never attached to non-image-titled IOs (METS.xml etc.)
 *  - if none available, a new file IO titled installation_view_NN.jpg is
 *    created under the artwork's first AIP IO (fallback: Components node,
 *    then the artwork itself for stub works)
 *
 * Identifier aliases: asset folders are named by MoMA objectId; two DRMC
 * stub works use different identifiers (169996 -> 102345 Space Invaders,
 * 143751 -> 103456 Official Welcome).
 *
 * Derivatives (thumbnail/reference) are generated by QubitDigitalObject
 * (requires ImageMagick, available in the app container).
 *
 * Run: php symfony binder:attach-drmc-assets
 * Then: php symfony search:populate
 *
 * @package    symfony
 * @subpackage task
 */
class arDrmcAttachAssetsTask extends sfBaseTask
{
  protected function configure()
  {
    $this->addOptions(array(
      new sfCommandOption('application', null, sfCommandOption::PARAMETER_OPTIONAL, 'The application name', 'qubit'),
      new sfCommandOption('env', null, sfCommandOption::PARAMETER_REQUIRED, 'The environment', 'cli'),
    ));

    $this->namespace = 'binder';
    $this->name = 'attach-drmc-assets';

    $this->briefDescription = 'Attach demo artwork images to seeded file IOs as digital objects';
    $this->detailedDescription = <<<EOF
Scans uploads/r/drmc-assets/{identifier}/ for image files and attaches them
as master digital objects (with generated thumbnail derivatives) to the
artwork's file IOs. Idempotent. Run search:populate afterwards to reindex.
EOF;
  }

  public function execute($arguments = array(), $options = array())
  {
    sfContext::createInstance($this->configuration);
    new sfDatabaseManager($this->configuration);

    sfConfig::add(arDrmcBootstrapTask::getDrmcConfigArray());

    $assetsDir = sfConfig::get('sf_web_dir').'/uploads/r/drmc-assets';
    if (!is_dir($assetsDir))
    {
      $this->logSection('binder', 'No assets directory at '.$assetsDir.' — nothing to do.');

      return;
    }

    $attached = 0;

    // Priority order first (Lovers, Grosse Fatigue, Manifestos 2), then the rest
    $identifiers = array();
    foreach (array('81362', '175938', '175258') as $preferred)
    {
      if (is_dir($assetsDir.'/'.$preferred))
      {
        $identifiers[] = $preferred;
      }
    }
    foreach (scandir($assetsDir) as $entry)
    {
      if ('.' == $entry[0] || !is_dir($assetsDir.'/'.$entry) || in_array($entry, $identifiers))
      {
        continue;
      }
      $identifiers[] = $entry;
    }

    // Asset dirs are named by MoMA objectId; these DRMC stubs use other ids
    $aliases = array(
      '169996' => '102345', // Space Invaders
      '143751' => '103456', // Official Welcome
    );

    foreach ($identifiers as $identifier)
    {
      $target = isset($aliases[$identifier]) ? $aliases[$identifier] : $identifier;
      $attached += $this->attachForArtwork($target, $assetsDir.'/'.$identifier);
    }

    $this->logSection('binder', 'Done: '.$attached.' digital object(s) attached.');
    if (0 < $attached)
    {
      $this->logSection('binder', 'Run "php symfony search:populate" to reindex.');
    }
  }

  protected function attachForArtwork($identifier, $dir)
  {
    $criteria = new Criteria;
    $criteria->add(QubitInformationObject::IDENTIFIER, $identifier);
    $criteria->add(QubitInformationObject::LEVEL_OF_DESCRIPTION_ID, sfConfig::get('app_drmc_lod_artwork_record_id'));
    if (null === $artwork = QubitInformationObject::getOne($criteria))
    {
      $this->logSection('binder', 'WARNING: no artwork with identifier '.$identifier.', skipping '.$dir);

      return 0;
    }

    // Collect image assets, sorted for stable ordering
    $images = array();
    foreach (scandir($dir) as $entry)
    {
      if (in_array(strtolower(pathinfo($entry, PATHINFO_EXTENSION)), array('jpg', 'jpeg', 'png')))
      {
        $images[] = $dir.'/'.$entry;
      }
    }
    sort($images);

    if (0 == count($images))
    {
      return 0;
    }

    $this->logSection('binder', $artwork->getTitle(array('sourceCulture' => true)).' ('.$identifier.'): '.count($images).' asset image(s)');

    // Names of digital objects already attached under this artwork (idempotency)
    $existingNames = array();
    foreach (QubitPdo::fetchAll(
      'SELECT do.name FROM digital_object do
         JOIN information_object io ON do.information_object_id = io.id
        WHERE io.lft >= ? AND io.rgt <= ?',
      array($artwork->lft, $artwork->rgt)) as $row)
    {
      $existingNames[] = $row->name;
    }

    // Candidate file IOs: digital-object-LOD descendants without a digital
    // object and with an image-extension title (never attach an image to a
    // METS.xml/.mov/.txt entry), stable nested-set order
    $candidates = array();
    foreach (QubitPdo::fetchAll(
      'SELECT io.id, i18n.title FROM information_object io
         JOIN information_object_i18n i18n ON io.id = i18n.id AND i18n.culture = io.source_culture
        WHERE io.lft > ? AND io.rgt < ? AND io.level_of_description_id = ?
          AND NOT EXISTS (SELECT 1 FROM digital_object do WHERE do.information_object_id = io.id)
        ORDER BY io.lft',
      array($artwork->lft, $artwork->rgt, sfConfig::get('app_drmc_lod_digital_object_id'))) as $row)
    {
      if (in_array(strtolower(pathinfo($row->title, PATHINFO_EXTENSION)), array('jpg', 'jpeg', 'png')))
      {
        $candidates[] = $row;
      }
    }

    $attached = 0;
    $pending = array();

    // Pass 1: pair assets with same-titled file IOs (version-specific
    // images, e.g. tetris-nes.jpg -> the NES component's file IO)
    foreach ($images as $path)
    {
      // Mirrors QubitDigitalObject::sanitizeFilename() (protected there)
      $sanitized = preg_replace('/[^a-z0-9_\.-]/i', '_', basename($path));
      if (in_array($sanitized, $existingNames))
      {
        $this->logSection('binder', '  [skip] '.basename($path).' already attached');

        continue;
      }

      $target = null;
      foreach ($candidates as $key => $candidate)
      {
        if ($candidate->title == basename($path) || $candidate->title == $sanitized)
        {
          $target = $candidate;
          unset($candidates[$key]);
          break;
        }
      }

      if (null === $target)
      {
        $pending[] = $path;

        continue;
      }

      $fileIo = QubitInformationObject::getById($target->id);
      $this->logSection('binder', '  [attach] '.basename($path).' -> file IO '.$fileIo->id.' ("'.$target->title.'") [name match]');
      $this->attachImage($fileIo, $path);
      $existingNames[] = $sanitized;
      $attached++;
    }

    // Pass 2: remaining assets to remaining candidates in order, then
    // new installation_view file IOs
    $candidates = array_values($candidates);
    foreach ($pending as $path)
    {
      $sanitized = preg_replace('/[^a-z0-9_\.-]/i', '_', basename($path));

      if (0 < count($candidates))
      {
        $target = array_shift($candidates);
        $fileIo = QubitInformationObject::getById($target->id);
        $this->logSection('binder', '  [attach] '.basename($path).' -> file IO '.$fileIo->id.' ("'.$target->title.'")');
      }
      else
      {
        $title = $this->nextInstallationViewTitle($artwork);
        $fileIo = $this->createFileIo($artwork, $title);
        $this->logSection('binder', '  [attach] '.basename($path).' -> new file IO '.$fileIo->id.' ("'.$title.'")');
      }

      $this->attachImage($fileIo, $path);
      $existingNames[] = $sanitized;
      $attached++;
    }

    return $attached;
  }

  protected function attachImage($fileIo, $path)
  {
    $digitalObject = new QubitDigitalObject;
    $digitalObject->informationObjectId = $fileIo->id;
    $digitalObject->usageId = QubitTerm::MASTER_ID;
    $digitalObject->assets[] = new QubitAsset($path);
    $digitalObject->indexOnSave = false;
    $digitalObject->save();
  }

  /**
   * Next unused installation_view_NN.jpg title under an artwork.
   */
  protected function nextInstallationViewTitle($artwork)
  {
    $rows = QubitPdo::fetchAll(
      'SELECT i18n.title FROM information_object io
         JOIN information_object_i18n i18n ON io.id = i18n.id AND i18n.culture = io.source_culture
        WHERE io.lft > ? AND io.rgt < ? AND i18n.title LIKE ?',
      array($artwork->lft, $artwork->rgt, 'installation_view_%'));

    $max = 0;
    foreach ($rows as $row)
    {
      if (1 === preg_match('/^installation_view_(\d+)/', $row->title, $matches))
      {
        $max = max($max, (int)$matches[1]);
      }
    }

    return sprintf('installation_view_%02d.jpg', $max + 1);
  }

  /**
   * Create a new file IO for an asset without a free candidate, under the
   * artwork's first AIP IO (fallback: Components node, then artwork itself).
   */
  protected function createFileIo($artwork, $filename)
  {
    $parentId = $artwork->id;

    $rows = QubitPdo::fetchAll(
      'SELECT id FROM information_object
        WHERE lft > ? AND rgt < ? AND level_of_description_id = ?
        ORDER BY lft LIMIT 1',
      array($artwork->lft, $artwork->rgt, sfConfig::get('app_drmc_lod_aip_id')));
    if (0 < count($rows))
    {
      $parentId = $rows[0]->id;
    }
    else
    {
      $criteria = new Criteria;
      $criteria->add(QubitInformationObject::PARENT_ID, $artwork->id);
      $criteria->add(QubitInformationObject::LEVEL_OF_DESCRIPTION_ID, sfConfig::get('app_drmc_lod_description_id'));
      if (null !== $components = QubitInformationObject::getOne($criteria))
      {
        $parentId = $components->id;
      }
    }

    $fileIo = new QubitInformationObject;
    $fileIo->parentId = $parentId;
    $fileIo->levelOfDescriptionId = sfConfig::get('app_drmc_lod_digital_object_id');
    $fileIo->setPublicationStatusByName('Published');
    $fileIo->title = $filename;
    $fileIo->indexOnSave = false;
    $fileIo->save();

    return $fileIo;
  }
}
